# filename: config.py
import pygame

SUITS = ['spades', 'hearts', 'diamonds', 'clubs']
NUMERIC_RANKS = ['2', '3', '4', '5', '6', '7', '8', '9', '10']
FACE_RANKS = ['jack', 'queen', 'king']
SPECIAL_RANKS = ['bonus_point']
ALL_RANKS = NUMERIC_RANKS + FACE_RANKS + SPECIAL_RANKS

CARD_VALUES = {
    '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10,
    'jack': 0, 'queen': 0, 'king': 0, 'bonus_point': 1
}

NUM_CARAVANS = 4
STARTING_HAND_SIZE = NUM_CARAVANS + 5
HAND_SIZE_LIMIT = 10
CARAVAN_WIN_MIN = 21
CARAVAN_WIN_MAX = 26
WINNING_CARAVANS_NEEDED = NUM_CARAVANS - 1

STANDARD_DECK_COMPOSITION = [{'rank': r, 'suit': s} for r in NUMERIC_RANKS for s in SUITS] + \
                            [{'rank': r, 'suit': s} for r in FACE_RANKS for s in SUITS]

AI_PAUSE_DURATION_MS = 750
AI_DIFFICULTY_LEVEL = 1

SCORE_WIN_LANE_WITH_KING = 350
SCORE_WIN_LANE = 305
SCORE_BREAK_OPPONENT_WINNING_LANE = 320
SCORE_SETUP_WIN = 245
SCORE_MAJOR_DISRUPTION = 80
SCORE_FLEXIBILITY_BONUS = 50
SCORE_KING_PROGRESS = 35
SCORE_BASIC_PROGRESS = 25
SCORE_QUEEN_SYNERGY_PER_CARD = 20

UTILITY_VALUE_QUEEN = 55
UTILITY_VALUE_JACK = 60
UTILITY_VALUE_KING = 65
UTILITY_VALUE_BONUS_POINT = 70

CHEAT_PROPHECY_SCORE_BONUS = 5000 #shhh dont look too closely into this

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
 
CARD_WIDTH = 100
CARD_HEIGHT = 150
CARD_SCALE_FACTOR = .9
SCALED_CARD_WIDTH = int(CARD_WIDTH * CARD_SCALE_FACTOR)
SCALED_CARD_HEIGHT = int(CARD_HEIGHT * CARD_SCALE_FACTOR)

OPPONENT_CARAVAN_Y = 60
PLAYER_CARAVAN_Y = SCREEN_HEIGHT - OPPONENT_CARAVAN_Y - SCALED_CARD_HEIGHT - 100
PLAYER_HAND_Y = SCREEN_HEIGHT - SCALED_CARD_HEIGHT - 20

HAND_REVEALED_Y = PLAYER_HAND_Y
HAND_HIDDEN_Y = PLAYER_HAND_Y + int(SCALED_CARD_HEIGHT * 0.70)

CARAVAN_START_X = 220
CARAVAN_SPACING = SCALED_CARD_WIDTH + 145

DECK_POS_X_OFFSET = 40
DECK_POS_PLAYER = (DECK_POS_X_OFFSET, PLAYER_CARAVAN_Y + SCALED_CARD_HEIGHT // 2 - SCALED_CARD_HEIGHT //2 )
DECK_POS_OPPONENT = (SCREEN_WIDTH - DECK_POS_X_OFFSET - SCALED_CARD_WIDTH, OPPONENT_CARAVAN_Y)

HAND_START_X = DECK_POS_PLAYER[0] + SCALED_CARD_WIDTH + 30
HAND_SPACING = SCALED_CARD_WIDTH * 0.8

BUTTON_WIDTH = 160
BUTTON_HEIGHT = 45
BUTTON_MARGIN = 8
BUTTON_START_X = SCREEN_WIDTH - BUTTON_WIDTH - 25
BUTTON_STACK_Y_START = PLAYER_CARAVAN_Y + SCALED_CARD_HEIGHT + 20
TUTORIAL_BUTTON_POS = (BUTTON_START_X, BUTTON_STACK_Y_START + (BUTTON_HEIGHT + BUTTON_MARGIN) * 0)
DISCARD_BUTTON_POS = (BUTTON_START_X, BUTTON_STACK_Y_START + (BUTTON_HEIGHT + BUTTON_MARGIN) * 1)
DISCARD_CARAVAN_BUTTON_POS = (BUTTON_START_X, BUTTON_STACK_Y_START + (BUTTON_HEIGHT + BUTTON_MARGIN) * 2)
PASS_BUTTON_POS = (BUTTON_START_X, BUTTON_STACK_Y_START + (BUTTON_HEIGHT + BUTTON_MARGIN) * 3)

WHITE = pygame.Color("white")
BLACK = pygame.Color("black")
RED = pygame.Color("red")
GREEN = pygame.Color("forestgreen")
BLUE = pygame.Color("cornflowerblue")
GOLD = pygame.Color("gold")
DARK_GRAY = pygame.Color(64, 64, 64)
LIGHT_GRAY = pygame.Color(200, 200, 200)
HIGHLIGHT_COLOR = pygame.Color(0, 200, 200, 150)
MESSAGE_BOX_COLOR = pygame.Color(50, 50, 50, 200)

ASSET_DIR = "assets"
BACKGROUND_IMAGE_FILE = "background.png"
CARD_BACK_IMAGE_FILE = "card_back.png"
BONUS_POINT_IMAGE_FILE = "free_point.png"
CARD_IMAGE_FORMAT = ".png"

FONT_NAME_CUSTOM = None
FONT_NAME_SYSTEM = 'arial'
FONT_SIZE_LARGE = 48
FONT_SIZE_MEDIUM = 28
FONT_SIZE_SMALL = 18

MESSAGE_BOX_RECT = pygame.Rect(0, 0, 650, 70)
MESSAGE_BOX_RECT.center = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 - 40)
WINNER_POS = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 + 60)
TURN_INFO_POS = (SCREEN_WIDTH // 2, 30)
INFO_MARGIN = 25
SOLD_COUNT_POS_P1 = (INFO_MARGIN, PLAYER_HAND_Y + SCALED_CARD_HEIGHT // 2 )
SOLD_COUNT_POS_P2 = (SCREEN_WIDTH - INFO_MARGIN, OPPONENT_CARAVAN_Y + SCALED_CARD_HEIGHT + 20)
CARAVAN_CARD_Y_OFFSET = int(SCALED_CARD_HEIGHT * 0.30) #offset

QUESTION_POPUP_RECT = pygame.Rect(0, 0, int(SCREEN_WIDTH * 0.7), int(SCREEN_HEIGHT * 0.6))
QUESTION_POPUP_RECT.center = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
QUESTION_TEXT_AREA_HEIGHT_RATIO = 0.35
QUESTION_OPTION_HEIGHT = 45
QUESTION_OPTION_MARGIN = 8
QUESTION_FEEDBACK_AREA_HEIGHT = 50
CARD_ANIMATION_DURATION_MS = 350
BONUS_POINT_ACTIVE_POS = (SCREEN_WIDTH - SCALED_CARD_WIDTH, SCREEN_HEIGHT // 2 - SCALED_CARD_HEIGHT // 4.5)

TOTAL_TUTORIAL_IMAGES = 16
TUTORIAL_IMAGE_BASE_NAME = "tutorial"
TUTORIAL_BTN_WIDTH = 120
TUTORIAL_BTN_HEIGHT = 40
TUTORIAL_BTN_MARGIN = 20
TUTORIAL_NAV_Y = SCREEN_HEIGHT - (TUTORIAL_BTN_HEIGHT // 2) - 20
TUTORIAL_PREV_BTN_CENTER_X = SCREEN_WIDTH // 2 - TUTORIAL_BTN_WIDTH - TUTORIAL_BTN_MARGIN
TUTORIAL_CLOSE_BTN_CENTER_X = SCREEN_WIDTH // 2
TUTORIAL_NEXT_BTN_CENTER_X = SCREEN_WIDTH // 2 + TUTORIAL_BTN_WIDTH + TUTORIAL_BTN_MARGIN